#-------------------------------------
# Another Makefile with macros
#-------------------------------------

JAVASRC   = FileTokens.java
SOURCES   = README Makefile $(JAVASRC)
MAINCLASS = FileTokens
CLASSES   = FileTokens.class
JARFILE   = FileTokens

all: $(JARFILE)
$(JARFILE): $(CLASSES)
	echo Main-class: $(MAINCLASS) > Manifest
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)
$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)
clean:
	rm $(CLASSES) $(JARFILE)
	
